#!/usr/bin/env bash
# Reproduction script generated by the `provenance` skill.
set -eo pipefail

uvx --from git+https://github.com/rhiza-research/chc-skills@dev chc-skills \
  mjo-forecast-fetch --bias-corrected --model gefs --output mjo_rmm_gefs.png