name: Daily ECMWF Download

permissions:
  contents: write

on:
  schedule:
    - cron: "16 00 * * *" # every day at 02:00 UTC
  workflow_dispatch: # allows manual run

jobs:
  download:
    runs-on: ubuntu-latest
    env:
      ECMWF_API_URL: ${{ secrets.ECMWF_API_URL }}
      ECMWF_API_KEY: ${{ secrets.ECMWF_API_KEY }}
      ECMWF_API_EMAIL: ${{ secrets.ECMWF_API_EMAIL }}
      TAHMO_API_PASSWORD: ${{ secrets.TAHMO_API_PASSWORD }}
      TAHMO_API_USERNAME: ${{ secrets.TAHMO_API_USERNAME }}
      EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD }}
      EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

            #- name: Install dependencies
            #  run: |
            #    pip install -r requirements.txt

            #- name: Run download script
            #  continue-on-error: true
            #  run: |
            #    python download_s2s.py

            #- name: Generate plots
            #  continue-on-error: true
            #  run: |
            #    python plot_s2s.py

            #- name: perform downscaling
            #  continue-on-error: true
            #  run: |
            #    python dowscale_dekade.py

            #- name: Save generated files in repo
            #  continue-on-error: true
            #  run: |
            #    git config user.name "github-actions[bot]"
            #    git config user.email "github-actions[bot]@users.noreply.github.com"
            #    git add plots/
            #    git add data/
            #    git commit -m "Daily automated update" || echo "No changes to commit"
            #    git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}

      
      - name: Install dependencies
        run: |
          pip install -r requirements_sheerwater.txt

      # Setup a local nuthatch cache so that subsequent days are faster
      - name: Cache nuthatch data
        uses: actions/cache/restore@v4
        with:
          path: ~/.nuthatch/caches
          key: nuthatch-

            #- name: download tahmo data
            #  uses: nick-fields/retry@v3
            #  continue-on-error: True
            #  with:
            #    timeout_minutes: 60
            #    max_attempts: 2
            #    command: |
            #      yes | python get_tahmo_data.py --country Kenya,Ghana,Senegal,Ethiopia

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true # Highly recommended for security

      - name: download IMERG satellite data
        uses: nick-fields/retry@v3
        continue-on-error: True
        with:
          timeout_minutes: 30
          max_attempts: 2
          command: |
            yes | python get_sat_data.py --country Kenya,Ghana,Senegal,Ethiopia --satellite imerg

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true # Highly recommended for security

            #- name: download CHIRPS satellite data
            #  uses: nick-fields/retry@v3
            #  continue-on-error: True
            #  with:
            #    timeout_minutes: 10
            #    max_attempts: 2
            #    command: |
            #      yes | python get_sat_data.py --country Kenya,Ghana,Senegal,Ethiopia --satellite chirps
            #
            
      # SAve the nuthatch cache
      - name: Cache nuthatch data
        uses: actions/cache/save@v4
        with:
          path: ~/.nuthatch/caches
          key: nuthatch-${{ github.run_id }}
     

      - name: generate plots
        continue-on-error: true
        run: |
          yes | python plot_sat_vs_stations.py --country Kenya,Ghana,Senegal,Ethiopia

      - name: Upload files as artifact
        uses: actions/upload-artifact@v4
        with:
          name: s2s_data
          path: |
            plots/**/*.png
            private_plots/**/*.png
            private_data/**/*.csv

  email:
    needs: download
    strategy:
      matrix:
        include:
          - country: Kenya
            emails: >
              josh@rhizaresearch.org,
              #genevieve@rhizaresearch.org,
              #chriskngetich@gmail.com,
              #gacherujemimah@gmail.com,
              #mrforecasting@gmail.com,
              #koderaphillips@yahoo.com,
              #marykilavi@yahoo.com,
              #hwkimani1@gmail.com,
              #chrisfunk@ucsb.edu,
              #alec.jong@gmail.com,
              #uiyov@student.kit.edu,
              #sshukla@ucsb.edu 
          - country: Ghana
            emails: >
              josh@rhizaresearch.org,
              #genevieve@rhizaresearch.org,
              #C.M.Wainwright@leeds.ac.uk,
              #D.J.Parker@leeds.ac.uk
          - country: Senegal
            emails: >
              josh@rhizaresearch.org,
              #genevieve@rhizaresearch.org,
              #C.M.Wainwright@leeds.ac.uk,
              #D.J.Parker@leeds.ac.uk
          - country: Ethiopia
            emails: >
              josh@rhizaresearch.org,
              #genevieve@rhizaresearch.org,
              #katiekowal@uchicago.edu
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Get EMCWF lagged date
        id: ecmwf_date
        run: echo "::set-output name=date::$(date -d '2 days ago' +'%Y-%m-%d')"

      - name: Download files as artifact
        uses: actions/download-artifact@v4
        with:
          name: s2s_data

      - name: Email out generated plots in ${{ matrix.country }}
        uses: dawidd6/action-send-mail@v16
        with:
          server_address: smtp.resend.com
          server_port: 587
          username: resend
          password: ${{ secrets.RESEND_API_KEY }}
          subject: Daily S2S Outlook
          to: ${{ matrix.emails }}
          from: "${{ matrix.country }} Data Share <info@dashboards.rhizaresearch.org>"
          body: Attached are dekadal and weekly outlooks and historical station data related to the subseasonal forecast. You can also view the data (except for the station data) at ${{ github.server_url }}/${{ github.repository }}.
          reply_to: genevieve@rhizaresearch.org
          attachments: >
            plots/${{ matrix.country }}/${{ steps.ecmwf_date.outputs.date }}/dekadal/dekadal_precip.png, 
            plots/${{ matrix.country }}/${{ steps.ecmwf_date.outputs.date }}/weekly/weekly_precip.png, 
            plots/${{ matrix.country }}/${{ steps.ecmwf_date.outputs.date }}/dekadal/imerg_Kenya_dekadal.png, 
            plots/${{ matrix.country }}/${{ steps.ecmwf_date.outputs.date }}/weekly/imerg_Kenya_weekly.png, 
            plots/${{ matrix.country }}/${{ steps.ecmwf_date.outputs.date }}/dekadal/chirps_Kenya_dekadal.png, 
            plots/${{ matrix.country }}/${{ steps.ecmwf_date.outputs.date }}/weekly/chirps_Kenya_weekly.png, 
            private_plots/${{ matrix.country }}/${{ steps.date.outputs.date }}/*.png, 
            private_data/station_data/${{ matrix.country }}/${{ steps.date.outputs.date }}/*.csv
